pull_request_rules:
  - name: automatically merge dependabot docs PRs
    conditions:
      - author=dependabot[bot]
      - check-success=Generate Microsite
      - base=docs
    actions:
      merge:
        method: merge
